name: Build, Test

on:
  [push]
  # push:
  #   branches:
  #     - main

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      API_URL: "12312"
      CURRENCY_CACHE_TIME_IN_HOURS: 24
      CURRENCY_RATE_CACHE_TIME_IN_HOURS: 1
      CCOMMAND_HISTORY_CACHE_TIME_IN_HOURS: 72

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable

    - name: Build and test code
      run: |
        cargo build --verbose
        cargo test --verbose
