name: Build, Test

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      API_KEY: ${{ secrets.API_KEY }}
      CURRENCY_CACHE_TIME_IN_HOURS: 24
      CURRENCY_RATE_CACHE_TIME_IN_HOURS: 1
      COMMAND_HISTORY_CACHE_TIME_IN_HOURS: 72

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable

    - name: Build, format, lint & test code
      run: |
        echo "API_KEY=$API_KEY" >> .env
        echo "CURRENCY_CACHE_TIME_IN_HOURS=$CURRENCY_CACHE_TIME_IN_HOURS" >> .env
        echo "CURRENCY_RATE_CACHE_TIME_IN_HOURS=$CURRENCY_RATE_CACHE_TIME_IN_HOURS" >> .env
        echo "COMMAND_HISTORY_CACHE_TIME_IN_HOURS=$COMMAND_HISTORY_CACHE_TIME_IN_HOURS" >> .env

        cargo build --verbose
        cargo fmt --verbose
        cargo clippy --verbose
        cargo test --verbose
     
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        
    - name: Build and push Docker images
      uses: docker/build-push-action@v3
      with:
        push: true
        platforms: linux/amd64
        tags: ${{ secrets.DOCKER_USERNAME }}/currency_converter_cli:latest